# This workflow exports the yaml sxl to excel

name: Export SXL TLC 1.1 to Excel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  repository_dispatch:

jobs:
  build-sxl-excel-tlc:
    runs-on: ubuntu-latest
    steps:

    - name: Check out rsmp_schema repository
      uses: actions/checkout@v2
      with:
        repository: rsmp-nordic/rsmp_schema
        path: rsmp_schema

    - name: Check out sxl-tools repository
      uses: actions/checkout@v2
      with:
        repository: rsmp-nordic/sxl-tools
        path: sxl-tools

    - name: Install dependencies
      run: |-
        gem install rubyXL --user
        sudo apt install python3-xlsxwriter

    - name: Create xlsx template
      run: |
        sxl-tools/create_template.py \
          --num-grouped-objects 5 \
          --num-single-objects 510 \
          --num-alarms 26 \
          --num-statuses 54 \
          --num-command-functional-position 1 \
          --num-command-functional-state 1 \
          --num-command-maneuver 1 \
          --num-command-parameters 24 \
          --alarm-rvs 5 \
          --status-rvs 10 \
          --command-args 7 \
          --output template.xlsx

    - name: Export to xlsx
      run: |
        sxl-tools/yaml2xlsx.rb \
          --template template.xlsx \
          --stdout \
          --short-desc \
          --objects rsmp_schemas/tlc/1.1/sxl.yaml \
          --site sxl_tools/tlc/SXL_Traffic_Controller_ver_1_1-site.yaml \
          > sxl.xlsx


    - name: Upload Excel as artifact
      uses: actions/upload-artifact@v1
      with:
        name: Excel
        path: sxl.xlsx
