# This workflow updates the sphinx documentation and builds a website

name: Build SXL TLC 1.0.15

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  repository_dispatch:

jobs:
  build-sxl-tlc:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out rsmp_documentation repository
      uses: actions/checkout@v4
    - name: Check out rsmp_sxl_traffic_lights repository
      uses: actions/checkout@v4
      with:
        repository: rsmp-nordic/rsmp_sxl_traffic_lights
        path: rsmp_sxl_traffic_lights
        ref: 1.0.15
    - name: Use updated makefile
      run: |
        cp .github/makefiles/makefile-sxl-tlc-1.0.15 rsmp_sxl_traffic_lights/Makefile
    - name: Install dependencies
      run: |
        sudo add-apt-repository ppa:inkscape.dev/stable
        sudo apt-get update
        sudo apt-get -y install \
              python3-sphinx \
              python3-sphinx-rtd-theme \
              texlive \
              texlive-latex-extra \
              texlive-humanities \
              imagemagick \
              inkscape \
              librsvg2-bin \
              latexmk
    - name: Install dependencies for mscgen
      run: |
        sudo apt-get remove nginx
        sudo apt-get remove libgd3
        sudo apt-get -y install autoconf flex bison gcc make pkg-config libgd-dev
    - name: Clone mscgen
      run: git clone https://github.com/dok-net/mscgen.git
    - name: Fetch patch for mscgen (fixes issue under Ubuntu 20.04)
      run: |
        cp .github/patches/gd.diff mscgen
        cd mscgen
        patch -p1 <gd.diff
    - name: Compile and install mscgen
      run: |
        cd mscgen
        chmod +x autogen.sh
        chmod +x test/renderercheck.sh
        ./autogen.sh
        autoupdate
        ./configure
        make
        make check
        sudo make install
    - name: Build rsmp_sxl_traffic_lights repository
      run: |
        cd rsmp_sxl_traffic_lights
        make html latexpdf
    - name: Commit documentation changes
      run: |
        mkdir -p docs/rsmp_sxl_traffic_lights/1.0.15
        cp -r rsmp_sxl_traffic_lights/build/html/* docs/rsmp_sxl_traffic_lights/1.0.15
        git pull -q
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/rsmp_sxl_traffic_lights/1.0.15
        git commit -m "Update documentation" -a || true
        # The above will fail if no changes were present, so
        # we ignore the return code.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: main
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload PDF as artifact
      uses: actions/upload-artifact@v4
      with:
        name: PDF
        path: rsmp_sxl_traffic_lights/build/latex/sxl-tlc.pdf
