# This workflow updates the sphinx documentation and builds a website

name: Build SXL TLC 1.2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  repository_dispatch:

jobs:
  build-sxl-tlc:
    runs-on: ubuntu-latest
    steps:
    - name: Check out rsmp_documentation repository
      uses: actions/checkout@v3
    - name: Check out rsmp_sxl_traffic_lights repository
      uses: actions/checkout@v3
      with:
        repository: rsmp-nordic/rsmp_sxl_traffic_lights
        path: rsmp_sxl_traffic_lights
        ref: 1.1.1
    - name: Install dependencies
      run: |
        sudo add-apt-repository ppa:inkscape.dev/stable
        sudo apt-get update
        sudo apt-get -y install \
              python3-sphinx \
              python3-sphinx-rtd-theme \
              texlive \
              texlive-latex-extra \
              texlive-humanities \
              texlive-fonts-extra \
              imagemagick \
              inkscape \
              librsvg2-bin \
              latexmk \
              mscgen
    - name: Build rsmp_sxl_traffic_lights repository
      run: |
        cd rsmp_sxl_traffic_lights
        make html latexpdf
    - name: Commit documentation changes
      run: |
        mkdir -p docs/rsmp_sxl_traffic_lights/1.2
        cp -r rsmp_sxl_traffic_lights/build/html/* docs/rsmp_sxl_traffic_lights/1.2
        git pull -q
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/rsmp_sxl_traffic_lights/1.1.1
        git commit -m "Update documentation" -a || true
        # The above will fail if no changes were present, so
        # we ignore the return code.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: main
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload PDF as artifact
      uses: actions/upload-artifact@v1
      with:
        name: PDF
        path: rsmp_sxl_traffic_lights/build/latex/sxl-tlc.pdf

  build-sxl-excel-tlc:
    runs-on: ubuntu-latest
    steps:

    - name: Check out rsmp_schema repository
      uses: actions/checkout@v3
      with:
        repository: rsmp-nordic/rsmp_schema
        path: rsmp_schema
        ref: 1.1.1

    - name: Check out sxl-tools repository
      uses: actions/checkout@v3
      with:
        repository: rsmp-nordic/sxl-tools
        path: sxl-tools

    - name: Install dependencies
      run: |-
        gem install rubyXL --user
        sudo apt install python3-xlsxwriter

    - name: Create xlsx template
      run: |
        sxl-tools/create_template.py \
          --num-grouped-objects 5 \
          --num-single-objects 510 \
          --num-alarms 26 \
          --num-statuses 54 \
          --num-command-functional-position 1 \
          --num-command-functional-state 1 \
          --num-command-maneuver 1 \
          --num-command-parameters 24 \
          --alarm-rvs 5 \
          --status-rvs 10 \
          --command-args 7 \
          --output template.xlsx

    - name: Export to xlsx
      run: |
        sxl-tools/yaml2xlsx.rb \
          --template template.xlsx \
          --stdout \
          --short-desc \
          --objects rsmp_schema/schemas/tlc/1.1.1/sxl.yaml \
          --site sxl-tools/tlc/SXL_Traffic_Controller_ver_1_1-site.yaml \
          > sxl.xlsx

    - name: Upload Excel as artifact
      uses: actions/upload-artifact@v1
      with:
        name: Excel
        path: sxl.xlsx
